# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup SQLite
      uses: ccorsi/setup-sqlite@v1
    - name: Create Database
      run: |
          sqlite3 belegocr.db < Data/SqlLite/schema.sql
          sqlite3 belegocr.db < Data/SqlLite/seed_techsolutions_template.sql
          sqlite3 belegocr.db < Data/SqlLite/migration_add_anchors.sql

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build  --no-restore 
    - name: Test
      run: dotnet test  --no-build --verbosity normal
